# Creacion e indexacion



1. Crea un array 1D con 50 valores aleatorio del 10 al 99. Accede a los elementos en las posiciones múltiplos de 5.


In [1]:
import numpy as np

In [8]:
array_uni = np.arange(10, 100,5)
array_uni

array([10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80, 85, 90,
       95])

2. Crea un array 1D con 30 valores del 1 al 20 (ambos incluidos). Utiliza indexación para obtener los elementos en las posiciones impares.

In [16]:
array_uni1 = np.arange(0, 21)
array_uni1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20])

In [17]:
print(f"Elementos que están en posición impar: \n {array_uni1[1::2]}")

Elementos que están en posición impar: 
 [ 1  3  5  7  9 11 13 15 17 19]


3. Crea un array 2D de forma (4, 6) con números aleatorios decimales (no deben estar comprendidos solo entre 0 y 1). Accede a la última fila de la matriz. Los decimales deben estar redondeados a 2 decimales.

In [21]:
array_bi1 = np.random.random_sample((4,6))
array_bi1

array([[0.11895343, 0.09741882, 0.54705108, 0.16661387, 0.29559507,
        0.38448665],
       [0.04453447, 0.28688571, 0.79619408, 0.17068274, 0.98449725,
        0.25691246],
       [0.25175278, 0.28028823, 0.80857705, 0.16715076, 0.43353027,
        0.32874062],
       [0.10708288, 0.09838776, 0.2524363 , 0.03727288, 0.92042682,
        0.08359101]])

In [24]:
redondeo = np.round(array_bi1, 2)

print(f'ultima fila de la matriz: {redondeo[-1]}')


ultima fila de la matriz: [0.11 0.1  0.25 0.04 0.92 0.08]


4. BONUS: Crea un array 3D de forma (2, 3, 5) y 30 elementos con números enteros entre 0 y 100 (ambos incluidos). Reemplaza los elementos en posiciones múltiplos de 3 por 0.

# Reshape y Transpose

## Ejercicios reshape

1. Crea un array 3D de forma (2, 3, 4) con valores aleatorios entre 1 y 100 (ambos inclusive). Utiliza reshape para convertirlo en un array 2D. Deberás pensar en la forma que es correcta para hacer este cambio.

In [26]:
array_tri = np.random.randint(1,101, (2,3,4))
array_tri

array([[[ 72,  32,  78,  65],
        [ 87,  19,  36, 100],
        [ 94,  42,  11,  47]],

       [[ 60,  81,  55,  31],
        [ 25,  99,  21,  73],
        [ 99,   7,  48,   7]]])

In [34]:
tri_reshape = np.reshape(array_tri, (2,12))

tri_reshape

array([[ 72,  32,  78,  65,  87,  19,  36, 100,  94,  42,  11,  47],
       [ 60,  81,  55,  31,  25,  99,  21,  73,  99,   7,  48,   7]])

2. Crea un array 3D de forma (3, 4, 5) con valores enteros del 1 al 61 (sin incluir). Utiliza reshape para convertirlo en un array 2D.

In [39]:
array_tri2 = np.random.randint(1,61, (3,4,5))
array_tri2

array([[[ 9, 39, 52, 24, 27],
        [36, 24, 20, 53, 17],
        [34,  3, 26,  8, 59],
        [43, 25, 50, 51, 41]],

       [[42, 53, 47, 18, 48],
        [58, 31, 37,  8, 59],
        [57, 48, 16, 19, 20],
        [54, 36, 38, 14, 35]],

       [[55, 10, 59, 43, 45],
        [11, 46,  8, 25, 20],
        [40, 53, 49, 41, 32],
        [28, 56, 11, 11, 39]]])

In [40]:
bi_reshape = np.reshape(array_tri2, (2,30))

bi_reshape

array([[ 9, 39, 52, 24, 27, 36, 24, 20, 53, 17, 34,  3, 26,  8, 59, 43,
        25, 50, 51, 41, 42, 53, 47, 18, 48, 58, 31, 37,  8, 59],
       [57, 48, 16, 19, 20, 54, 36, 38, 14, 35, 55, 10, 59, 43, 45, 11,
        46,  8, 25, 20, 40, 53, 49, 41, 32, 28, 56, 11, 11, 39]])

## Ejercicios transpose

3. Utiliza el array 3D del ejercicio 2 de reshape. Utiliza transpose para permutar los ejes y obtener un nuevo array con forma (5, 4, 3).

In [41]:
array_tri2 = np.random.randint(1,61, (3,4,5))
array_tri2

array([[[55, 23, 37, 56,  9],
        [57, 15, 42, 48, 48],
        [35, 36, 46, 37, 51],
        [ 2, 54, 28, 43,  3]],

       [[ 3, 31, 37, 54, 30],
        [51, 51, 50, 26, 53],
        [41, 49, 55, 25, 50],
        [36, 58, 20, 19, 26]],

       [[50, 51, 42, 49, 30],
        [39,  5, 53, 24, 33],
        [54, 15, 10, 28, 47],
        [18, 36, 11, 37, 35]]])

In [46]:
tri_trans = np.transpose(array_tri2) 
tri_trans

array([[[55,  3, 50],
        [57, 51, 39],
        [35, 41, 54],
        [ 2, 36, 18]],

       [[23, 31, 51],
        [15, 51,  5],
        [36, 49, 15],
        [54, 58, 36]],

       [[37, 37, 42],
        [42, 50, 53],
        [46, 55, 10],
        [28, 20, 11]],

       [[56, 54, 49],
        [48, 26, 24],
        [37, 25, 28],
        [43, 19, 37]],

       [[ 9, 30, 30],
        [48, 53, 33],
        [51, 50, 47],
        [ 3, 26, 35]]])

4. Utiliza el array 3D del ejercicio 2 de reshape. Utiliza transpose para cambiar el orden de los ejes y obtener un nuevo array con forma (3, 5, 4).

In [47]:
array_tri2 = np.random.randint(1,61, (3,4,5))
array_tri2

array([[[10, 42, 19, 59, 14],
        [24, 27, 32, 15, 31],
        [10, 46, 14, 22, 56],
        [25, 23, 54, 41, 58]],

       [[ 5, 55, 39, 38,  9],
        [33, 23, 16,  8, 43],
        [40, 60, 13, 27, 39],
        [ 3, 26, 40, 55, 30]],

       [[55,  9, 49, 13, 13],
        [25, 35, 42, 43, 18],
        [55, 32,  9, 30, 21],
        [53,  1, 13, 30, 11]]])

In [51]:
tri_trans3 = np.transpose(array_tri2, (3,5,4)) 
tri_trans3

AxisError: axis 3 is out of bounds for array of dimension 3

In [ ]:
transpose1 = np.transpose(array_tri2())

# Funciones Aritméticas y Estadísticas:

1. Crea un array de tres 3D con elementos entre el 0 y 1 de forma (2, 3, 5) cuyos valores solo tengan 1 decimal.

In [56]:
tridimensional = np.random.random_sample((2,3,5))

tri_red = np.round(tridimensional, 1)

tri_red

array([[[0.1, 0.7, 0.9, 0.1, 0.6],
        [0.2, 0.8, 0.5, 0.6, 0.5],
        [0.9, 0.5, 0.4, 0.1, 0.7]],

       [[0.9, 0.2, 0. , 0.1, 0.6],
        [0.7, 0.1, 0.8, 0.7, 0.9],
        [0.8, 0.1, 0.6, 0.5, 0.2]]])

2. Crea un array vacío con la misma forma y dimensiones que el array creado anteriormente. Vamos a reemplazar los valores de la matriz vacía que nos acabamos de crear pero basándonos en los valores del primer array bajo las siguientes condiciones:

Si el valor del array es igual que la media, se reemplaza por "A".

Si el valor del array es mayor que la media, se reemplaza por "B".

Si el valor del array es menor que la media, se reemplaza por "C".

Si el valor es igual que el máximo, se reemplaza por "D".

Si el valor es igual que el mínimo, se reemplaza por "E".

In [58]:
vacio = np.empty((2,3,5))
vacio

array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]])

In [60]:
media_vacio = np.mean(tri_red)
media_vacio

0.4933333333333333

In [61]:
max_ej1 = np.max(tri_red)
max_ej1

0.9

In [63]:
min_ej1 = np.min(tri_red)
min_ej1

0.0

hacer un bucle for